### PR TITLE
Merge local changes

### PR DESCRIPTION
**Pull request by schooft**
Various changes from the local version.

### CODE REVIEW

**Review by MEATDESY — APPROVED** [review]
Wow, these are many changes between the versions. As long as all changes from the local emacontrol to the github project are there, it should be fine.

**Comment by MEATDESY** [comment]
Okay one has to check why the checks failed?

**Comment by schooft** [comment]
> Okay one has to check why the checks failed?

The changes in this PR changed the API, but the tests have not been updated. I will see if I can fix them.

**Comment by MEATDESY** [comment]
Okay, as long this is only a problem of the tests and not the actual code, everything is fine. I leave it up to you if you want to invest time to fix this.

**Comment by schooft** [comment]
I just fixed the test failures but didn't check if the tests still make sense.

**Comment by MEATDESY** [comment]
Cool, then we can merge.

**Pull request merged**
